image: docker:git

services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u _json_key -p "$CI_CONTAINER_REGISTRY_TOKEN" https://eu.gcr.io

variables:
  DOCKER_HOST: 'tcp://localhost:2375'
  DOCKER_DRIVER: 'overlay'

build-tagged:
  stage: build
  only:
    - tags
  script:
    - export MAJOR="$(echo $CI_COMMIT_TAG | cut -d'.' -f1)"
    - export MINOR="$(echo $CI_COMMIT_TAG | cut -d'.' -f2)"
    - docker build -t eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} .
    - docker push eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG}
    - docker tag eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} eu.gcr.io/flownative-beach/beach-nginx:${MAJOR}
    - docker push eu.gcr.io/flownative-beach/beach-nginx:${MAJOR}
    - docker tag eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} eu.gcr.io/flownative-beach/beach-nginx:${MAJOR}.${MINOR}
    - docker push eu.gcr.io/flownative-beach/beach-nginx:${MAJOR}.${MINOR}
    - docker tag eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} eu.gcr.io/flownative-beach/beach-nginx:latest
    - docker push eu.gcr.io/flownative-beach/beach-nginx:latest
    - docker login -u "$DOCKER_IO_REGISTRY_USER" -p "$DOCKER_IO_REGISTRY_PASSWORD" $DOCKER_IO_REGISTRY
    - docker tag eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} docker.io/flownative/beach-nginx:${MAJOR}
    - docker push docker.io/flownative/beach-nginx:${MAJOR}
    - docker tag eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} docker.io/flownative/beach-nginx:${MAJOR}.${MINOR}
    - docker push docker.io/flownative/beach-nginx:${MAJOR}.${MINOR}
    - docker tag eu.gcr.io/flownative-beach/beach-nginx:${CI_COMMIT_TAG} docker.io/flownative/beach-nginx:latest
    - docker push docker.io/flownative/beach-nginx:latest
