include:
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.gitlab-ci.yml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.release-google.gitlab-ci.yml'
  - project: 'flownative/infrastructure/build-tools'
    file: '/gitlab-ci/docker.release-docker-io.gitlab-ci.yml'
