name: Release latest version to docker.io
on:
  schedule:
    - cron: '30 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: 'latest'

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Publish release to docker.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: 'yes'

          source_image_name: docker.pkg.github.com/flownative/docker-beach-nginx/beach-nginx
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: flownative/beach-nginx
          target_registry_username: ${{ secrets.DOCKER_IO_REGISTRY_USER }}
          target_registry_password: ${{ secrets.DOCKER_IO_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://index.docker.io/v1/
